import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#18171c',
    paddingHorizontal: 24,
    paddingTop: 40,
  },
  backButton: {
    marginBottom: 20,
    width: 40,
    height: 40,
    justifyContent: 'center'
  },
  backIcon: {
    color: '#a259ff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  title: {
    color: '#a259ff',
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 32,
  },
  avatarContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    position: 'relative',
    width: 150,
    height: 150,
    alignSelf: 'center',
  },
  avatar: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 2,
    borderColor: '#fff',
  },
  addPhotoCircle: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#fff',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    opacity: 0.7,
  },
  addPhotoIcon: {
    width: 22,
    height: 22,
    tintColor: '#bdbdbd',
    color: 'gray'
  },
  input: {
    backgroundColor: '#232228',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 14,
    color: '#fff',
    fontSize: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#232228',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#232228',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#232228',
  },
  flagButton: {
    marginRight: 8,
    color: '#fff',
  },
  callingCode: {
    color: '#fff',
    fontSize: 16,
    marginRight: 8,
  },
  phoneInput: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    marginBottom: 24,
  },
  forgotPasswordText: {
    color: '#4285F4',
    fontSize: 14,
  },
  loginButton: {
    backgroundColor: '#a259ff',
    borderRadius: 30,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 24,
    marginBottom: 18,
  },
  loginButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  orText: {
    color: '#fff',
    alignSelf: 'center',
    marginBottom: 18,
    fontSize: 16,
    marginTop: 24,
  },
  phoneLoginText: {
    color: '#4285F4',
    fontSize: 16,
    alignSelf: 'center',
    marginTop: 10,
  },
  termsText: {
    color: '#fff',
    fontSize: 12,
    textAlign: 'center',
    position: 'absolute',
    bottom: 30,
    left: 24,
    right: 24,
  },
  termsLink: {
    color: '#4285F4',
    textDecorationLine: 'underline',
  },
});
export default styles;